### ISSUE TITLE
Cannot make lgoudriaan's BuildAndQuery change work

### ISSUE THREAD

**Issue by rdehouss** [BlueBasher/WorkItemUpdater#155]
Hello,

Thx for this amazing extension!
I'm trying to use the work of @lgoudriaan made via the PR #124 without success.
It's like the line https://github.com/BlueBasher/WorkItemUpdater/blob/main/src/WorkItemUpdater.ts#L174 didn't exist :D

The installed version is 3.0.88 (Latest) as on this screnshot:
![image](https://github.com/user-attachments/assets/7457f181-c35f-480c-b15e-9cbc6e8e2622)

In the logs of the task, I have this "header":
```
Starting: Update Work Items
==============================================================================
Task         : WorkItem Updater
Description  : This task adds functionality to update WorkItems during a Build or Release.
Version      : 2.5.835
Author       : Blue Basher
Help         : 
==============================================================================
```
I have tried
```
- task: WorkItemUpdater@2
  displayName: Update Work Items
  inputs:
    workItemType: Epic
    workitemsSource: Build
    addTags: |
      test
  continueOnError: true
```
and
```
- task: WorkItemUpdater@2
  displayName: Update Work Items
  inputs:
    workItemType: Epic
    workitemsSource: Query
    workitemsSourceQuery: ...
    addTags: |
      test
  continueOnError: true
```
both works and work items are found and updated.
When I try with
```
- task: WorkItemUpdater@2
  displayName: Update Work Items
  inputs:
    workItemType: Epic
    workitemsSource: BuildAndQuery
    workitemsSourceQuery: ...
    addTags: |
      test
  continueOnError: true
```
I have in the logs
```
...
##[debug]Get WorkItemTrackingApi
##[debug]Get workItemsRefs
No workitems found to update.
```
while I have
```
...
##[debug]Get WorkItemTrackingApi
##[debug]Get workItemsRefs
Using Build as WorkItem Source
##[debug]Loop workItemsRefs
...
```
with `workitemsSource=Build`

From the code, I cannot understand why it's not working, it should work... Unless the deployed version is incorrect? I doubt it since the feature has been merged in 2023 and multiple deployments have been done so far.

Any idea?

Thanks in advance

Regards,

Raphaël
