### ISSUE TITLE
Work item is moved from done splitted column to not done when the option isn't set

### ISSUE THREAD

**Issue by Galad** [BlueBasher/WorkItemUpdater#54]
We have the a board column that is splitted in Doing / Done columns.
We use the task with the following configuration

```
  - task: WorkItemUpdater@2
    displayName: 'Update Bug (test)'
    inputs:
      workItemType: Bug
      linkBuild: true
```

When a work item is already in the Done column, the WorkItemUpdater task will move it back to the Doing column.

We expect that not setting anything in the YAML configuration won't change the state of this column.
