### ISSUE TITLE
##[error]TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by granicus422** [BlueBasher/WorkItemUpdater#95]
Getting the following error when trying to update a custom field value. using the below configuration:

```
- task: WorkItemUpdater@2
  inputs:
    workitemsSource: 'Build'
    workitemLimit: '999'
    updateAssignedTo: 'Never'
    updateFields: 'Microsoft.VSTS.Build.IntegrationBuild,Test Build'
```
